service: service-open-delivery

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket: deploy-bucket-loocal-lambda
  region: us-east-1
  versionFunctions: false

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"

functions:
  api:
    description: "API Serverless para integração open delivery"
    handler: src/lambda.handler
    environment:
      DB_USER: ${self:custom.${self:provider.stage}.DB_USER}
      DB_PASSWORD: ${self:custom.${self:provider.stage}.DB_PASSWORD}
      DB_HOST: ${self:custom.${self:provider.stage}.DB_HOST}
      DB_NAME: ${self:custom.${self:provider.stage}.DB_NAME}
      DB_PORT: ${self:custom.${self:provider.stage}.DB_PORT}
      JWT_SECRET: ${self:custom.${self:provider.stage}.JWT_SECRET}
      LOOCAL_API_URL: ${self:custom.${self:provider.stage}.LOOCAL_API_URL}
      LOOCAL_LOGIN_EMAIL: ${self:custom.${self:provider.stage}.LOOCAL_LOGIN_EMAIL}
      LOOCAL_LOGIN_PASSWORD: ${self:custom.${self:provider.stage}.LOOCAL_LOGIN_PASSWORD}
      ENV: ${self:custom.${self:provider.stage}.ENV}

    timeout: 60
    memorySize: 256
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  dev:
    stage: "dev"
    DB_USER: postgres
    DB_PASSWORD: "s4JY$C8&32!c"
    DB_HOST: loocal-api-prd-serverless.cluster-ceddyythm83e.us-east-1.rds.amazonaws.com
    DB_NAME: development
    DB_PORT: 5432
    JWT_SECRET: 45b683b47666acfb06e2c99cbb4b753c6b92f556929385d8b7a757cfff562a1b
    LOOCAL_API_URL: https://api-developer-backoffice.loocalapp.com/api
    LOOCAL_LOGIN_EMAIL: lucas2teste@loocal.online
    LOOCAL_LOGIN_PASSWORD: 123456
    ENV: dev

  prd:
    stage: "prod"
    DB_USER: postgres
    DB_PASSWORD: "s4JY$C8&32!c"
    DB_HOST: loocal-api-prd-serverless.cluster-ceddyythm83e.us-east-1.rds.amazonaws.com
    DB_NAME: postgres
    DB_PORT: 5432
    JWT_SECRET: 45b683b47666acfb06e2c99cbb4b753c6b92f556929385d8b7a757cfff562a1b
    LOOCAL_API_URL: https://api-production-backoffice.loocalapp.com/api
    LOOCAL_LOGIN_EMAIL: lucas.souza@loocal.online
    LOOCAL_LOGIN_PASSWORD: 123456
    ENV: prd

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  excludeDevDependencies: true
  exclude:
    - .vscode/**
    - '*/**/*.js.map'
    - coverage/**
    - dist/test/**
    - lib/**
    - temp/**
    - test/**
    - .git/**
    - docs/**
    - .github/**
    - .key.txt
    - deploy.txt
