export enum EventTypeEnum {
    CREATED = 'CREATED',
    CONFIRMED = 'CONFIRMED',
    PREPARATION_REQUESTED = 'PREPARATION_REQUESTED',
    PREPARING = 'PREPARING',
    READY_FOR_PICKUP = 'READY_FOR_PICKUP',
    DISPATCHED = 'DISPATCHED',
    PICKUP_AREA_ASSIGNED = 'PICKUP_AREA_ASSIGNED',
    PICKED_UP = 'PICKED_UP',
    DELIVERED = 'DELIVERED',
    CONCLUDED = 'CONCLUDED',
    CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED',
    CANCELLATION_REQUEST_DENIED = 'CANCELLATION_REQUEST_DENIED',
    CANCELLED = 'CANCELLED',
    ORDER_CANCELLATION_REQUEST = 'ORDER_CANCELLATION_REQUEST',
    CANCELLED_DENIED = 'CANCELLED_DENIED'
}

export const ALL_EVENT_TYPES = Object.values(EventTypeEnum);
